### ISSUE TITLE
Gracefully handle unsubscribe failures

### ISSUE THREAD

**Issue by annastoilova** [tiki/decision#12]
As a user, I want to know if I haven't managed to unsubscribe from a list. 

Currently I swipe left, and the app doesn't tell me anything so I think I have successfully unsubscribed.
-
Technical question: 
**Can we not display cards which we cannot unsubscribe the users from?**  Or at least make sure these cards appear last? Avoid / de-prioritise them.

**Comment by ricardobrg** [comment]
check in https://github.com/tiki/app/issues/355

**Comment by ricardobrg** [comment]
Closing, as not applicable now.
