### ISSUE TITLE
Create decision cards UI

### ISSUE THREAD

**Issue by sfaria27** [tiki/decision#2]
Create default decision card UI with swipe callbacks

Acceptance criteria:
1. decision card UI that renders any widget inside of it
2. swipe animation with left and right tilting
3. dragging and release animation 
4. swipe callback actions for left/right up/down

**Comment by ricardobrg** [comment]
![Simulator Screen Shot - iPhone 6s - 2022-03-08 at 06 06 57](https://user-images.githubusercontent.com/8357343/157204389-ce9681fb-d048-4fc4-b1c1-722039244262.png)
