### ISSUE TITLE
Integrate decision card SDK into app

### ISSUE THREAD

**Issue by sfaria27** [tiki/decision#6]
Replace decision screen slice with decision card SDK

Acceptance criteria:
1. App running with decision screen provided by decision card SDK

**Comment by ricardobrg** [comment]
integrating spam cards generation

**Comment by sfaria27** [comment]
@ricardobrg to add screenshots

**Comment by ricardobrg** [comment]
![Simulator Screen Recording - iPhone 13 - 2022-03-08 at 15 47 42](https://user-images.githubusercontent.com/8357343/157305180-54233ac8-08ef-4a8f-b61f-8a586f0cdde0.gif)
